# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YnpvDU52pBNyDgmVew1K5dqdg_Q9nFn7
"""

import pandas as pd
data={
    'Devices':['device1','device2','device3'],
    'Usage':[3,4,2],
    'Iot_sensors':[2,3,4]
}
df=pd.DataFrame(data)
df['Total usage'] = df['Usage'] + df['Iot_sensors']
print(df)
import matplotlib.pyplot as plt
real_time=[2,3,6]
total_usage=[5,6,7]
maximum_demand=[6,7,8]
plt.plot(real_time,total_usage,marker='o')
plt.xlabel('real time(s)')
plt.ylabel('total usage')
plt.title("real time vs total usage curve")
plt.show()
plt.plot(real_time,maximum_demand,marker='o')
plt.xlabel('real time(s)')
plt.ylabel('maximum demand')
plt.title("real time vs maximum demand curve")
plt.show()